keycloak:
   auth-server-url: http://127.0.0.1:8080/auth/
   realm: fhircore
#   ssl-required: external
   resource: fhircore-client
   credentials:
      secret: 9a666b97-92f5-4995-a2d3-83d75f5a98c1
#   confidential-port: 0
#   enabled: true
#   public-client: true
#   policy-enforcer-config.enforcement-mode: PERMISSIVE
#  bearer-only: true
#  security-constraints[0]:
#    - authRoles[0]: fhirrole
#    securityCollections[0].patterns[0]: /fhir/*
