hapi:
  fhir:
    version: dstu3
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jersey
      server-version: 1.0.0
      implementation-description: Spring Boot Jersey Server Sample
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    keycloak:
       realm: fhircore
server.port: 8087
management:
  security:
    enabled: true
logging:
  level:
    ca.uhn.fhir.jaxrs: debug
    org.keycloak: debug
    org.spingframework: debug
keycloak:
   auth-server-url: http://localhost:8080/auth/
   realm: fhircore
   ssl-required: external
   resource: fhircore-client
   credentials:
      secret: 9a666b97-92f5-4995-a2d3-83d75f5a98c1
   confidential-port: 0
   enabled: true
   public-client: true
   bearer-only: true
#   security-constraints:
#      -  auth-roles:
#            - "*"
#      security-collections:
#         -  name:
#            patterns:
#               - /*

