hapi:
  fhir:
    version: dstu3
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jersey
      server-version: 1.0.0
      implementation-description: Spring Boot Jersey Server Sample
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    keycloak:
       realm: Opensrp
management:
  security:
    enabled: false
logging:
  level:
    ca.uhn.fhir.jaxrs: debug
    org.keycloak: debug
keycloak:
   auth-server-url: http://localhost:8181/auth/
   realm: Opensrp
   ssl-required: external
   resource: opensrp-server
   credentials:
      secret: b30a2b3a-f56e-483f-9ca7-e428a651b88d
   confidential-port: 0
   enabled: true
   public-client: true
   bearer-only: true
#   security-constraints:
#      -  auth-roles:
#            - "*"
#      security-collections:
#         -  name:
#            patterns:
#               - /*


